#!/usr/bin/env python3
"""
GSA state 파일 + log 파일 업데이트.

드래프트 생성 또는 스킵 이후 호출. 두 가지 기록:
  1. state file (JSON) — 기계 판단용: used_sources dedup, last_run, last_draft_at
  2. log file (Markdown) — 사람이 훑어보는 append-only 실행 로그

Usage:
  # 볼트 루트에서 실행
  python3 _LifeOS_/Skills/gobi-social-agent/scripts/update_state.py \
    --source "AI/Analysis/YYYY-MM-DD - Agent.md" \
    --draft "_Gobi_/GSA/YYYY-MM-DD title - BU.md" \
    --kind bu

  # 스킵 기록
  python3 update_state.py --kind skip --draft "" --note "no new signals"
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

MAX_HISTORY = 200

LOG_HEADER = """# GSA Log

Append-only execution log. Latest runs at top. Generated by `update_state.py`.

| Timestamp | Kind | Draft | Sources | Note |
|---|---|---|---|---|
"""

HEADER_SEP = "|---|---|---|---|---|\n"


def _parse_frontmatter(text: str) -> dict:
    """Tiny frontmatter parser (YAML-lite).

    Avoids external deps (pyyaml). Supports:
    - key: value
    - key: "value"
    - key:\n  - item
    """
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm_block = text[3:end].strip("\n")
    data: dict = {}
    current_key: str | None = None
    for raw in fm_block.splitlines():
        line = raw.rstrip("\n")
        if not line.strip():
            continue
        if line.startswith("  - ") and current_key:
            item = line[4:].strip().strip('"')
            cur = data.get(current_key)
            if isinstance(cur, list):
                cur.append(item)
            elif cur is None:
                data[current_key] = [item]
            else:
                # previously parsed as scalar; upgrade to list
                data[current_key] = [str(cur), item]
            continue
        if ":" in line and not line.startswith(" "):
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip().strip('"')
            current_key = key
            data[key] = value if value != "" else []
    return data


_TOPIC_KEYWORDS = [
    # EN
    "inbox",
    "bucket",
    "river",
    "flow",
    "legacy",
    "retriev",  # retrievable/retrievability
    "merge",
    "connect",
    # KO
    "강물",
    "흐름",
    "레거시",
    "부채",
    "부채감",
    "정리",
    "비우",
    "회수",
]


def _topic_signature(text: str) -> list[str]:
    t = (text or "").lower()
    sig: list[str] = []
    for kw in _TOPIC_KEYWORDS:
        if kw.lower() in t:
            sig.append(kw)
    # de-dupe while preserving order
    return list(dict.fromkeys(sig))


def append_log(log_path: Path, ts: str, kind: str, draft: str,
               sources: list[str], note: str) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    if not log_path.exists():
        log_path.write_text(LOG_HEADER, encoding="utf-8")
    text = log_path.read_text(encoding="utf-8")
    if HEADER_SEP not in text:
        text = LOG_HEADER + text.lstrip()
    sep_idx = text.find(HEADER_SEP)
    rows_start = sep_idx + len(HEADER_SEP) if sep_idx != -1 else len(text)
    draft_cell = f"`{draft}`" if draft else "—"
    sources_cell = ", ".join(f"`{s}`" for s in sources) if sources else "—"
    note_cell = note.replace("|", "\\|") if note else "—"
    row = f"| `{ts}` | **{kind}** | {draft_cell} | {sources_cell} | {note_cell} |\n"
    text = text[:rows_start] + row + text[rows_start:]
    log_path.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Update GSA state + log after draft creation")
    parser.add_argument("--source", action="append", default=[], help="source file path (repeatable)")
    parser.add_argument("--draft", required=True, help="created draft path ('' for skip)")
    parser.add_argument("--kind", choices=["bu", "thread", "reply", "skip"], required=True)
    parser.add_argument("--state", type=Path, default=None,
                        help="state file path (default: <cwd>/_LifeOS_/Skills/gobi-social-agent/state/_state.json)")
    parser.add_argument("--log", type=Path, default=None,
                        help="log file path (default: <cwd>/_LifeOS_/Skills/gobi-social-agent/state/_log.md)")
    parser.add_argument("--note", default="", help="optional note (e.g. skip reason)")
    parser.add_argument("--replied-to", action="append", default=[],
                        help="Gobi space-post ID just replied to (repeatable; "
                             "for reply-kind drafts — dedups future runs)")
    args = parser.parse_args()

    state_path: Path = args.state or (Path.cwd() / "_LifeOS_/Skills/gobi-social-agent/state/_state.json")
    log_path: Path = args.log or (Path.cwd() / "_LifeOS_/Skills/gobi-social-agent/state/_log.md")
    state_path.parent.mkdir(parents=True, exist_ok=True)

    if state_path.exists():
        try:
            state = json.loads(state_path.read_text())
        except json.JSONDecodeError:
            state = {}
    else:
        state = {}

    now = datetime.now(tz=timezone.utc).astimezone().isoformat(timespec="minutes")
    state["last_run"] = now
    if args.kind != "skip":
        state["last_draft_at"] = now

    used = list(dict.fromkeys((state.get("used_sources") or []) + args.source))
    state["used_sources"] = used[-MAX_HISTORY:]

    if args.replied_to:
        replied = list(dict.fromkeys(
            (state.get("replied_to_posts") or []) + [str(x) for x in args.replied_to]
        ))
        state["replied_to_posts"] = replied[-MAX_HISTORY:]

    # Similar-topic dedup support (best-effort): store metadata about recent replies
    # so collect_signals can suppress "same author + same space + similar topic" replies.
    if args.kind == "reply" and args.draft:
        try:
            draft_text = Path(args.draft).read_text(encoding="utf-8")
        except OSError:
            draft_text = ""
        fm = _parse_frontmatter(draft_text) if draft_text else {}
        space_slug = str(fm.get("reply_to_space") or "").strip() or None
        author = str(fm.get("reply_to_author") or "").strip() or None
        thread_id = str(fm.get("reply_to_thread") or "").strip() or None
        title = str(fm.get("title") or "").strip() or None
        context_lines = fm.get("community_context") if isinstance(fm.get("community_context"), list) else []
        ctx = "\n".join(str(x) for x in context_lines)
        sig = _topic_signature("\n".join([title or "", ctx, args.note or ""]))

        if space_slug or author or thread_id or sig:
            recent = state.get("recent_reply_topics") or []
            if not isinstance(recent, list):
                recent = []
            recent.append({
                "ts": now,
                "space_slug": space_slug,
                "author": author,
                "post_id": thread_id,  # target post id
                "title": title,
                "topic_sig": sig,
            })
            state["recent_reply_topics"] = recent[-MAX_HISTORY:]

    history = state.setdefault("history", [])
    history.append({
        "ts": now,
        "kind": args.kind,
        "draft": args.draft,
        "sources": args.source,
        "note": args.note,
    })
    state["history"] = history[-MAX_HISTORY:]

    state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2))
    append_log(log_path, now, args.kind, args.draft, args.source, args.note)

    print(json.dumps({
        "ok": True,
        "state": str(state_path),
        "log": str(log_path),
        "last_run": now,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
